#!/bin/bash

if [ "$1" = "test" ]; then
    echo "java -cp bin:audio.jar Test $2 $3 $4"
    shift 1
    java -cp bin:audio.jar Test "$@"
    exit
fi

if [ "$1" = "example" ]; then
    echo "java -cp bin:audio.jar Example $2 $3 $4"
    shift 1
    java -cp bin:audio.jar Example "$@"
    exit
fi

if [ "$1" = "l" ]; then
    shift 1
    echo "java -cp bin:audio.jar -cp bin:audio.jar be/uliege/straet/oop/filters2/Loader $@"
    java -cp bin:audio.jar be/uliege/straet/oop/filters2/Loader "$@"
    exit
fi



echo "java -cp bin:audio.jar $@"
java -cp bin:audio.jar "$@"
